const wiki = slug => `https://wiki.opensourceecology.org/wiki/${slug}`;
export const sources = [
  {id:'mission', title:'OSE Mission', slug:'OSE_Mission', kind:'Foundational reading', note:'The purpose: an economy built on openly shared knowledge and collaboration.'},
  {id:'change', title:'OSE Model of Change', slug:'OSE_Model_of_Change', kind:'Strategy / proposed model', note:'Learning communities that develop people, infrastructure and enterprises together.'},
  {id:'goals', title:'OSE Goals', slug:'OSE_Goals', kind:'Outline / needs development', note:'A founder-selected destination. The page had no substantive explanatory text when checked; do not infer targets from its title.'},
  {id:'franchise', title:'Philanthropic Franchise', slug:'Philanthropic_Franchise', kind:'Wiki-tagged OSE Canon', canon:true, note:'A proposed network of locally adapted campuses that reinvest productive surplus in public-purpose work.'},
  {id:'solar', title:'Open Source Solar Microfactory', slug:'Open_Source_Solar_Microfactory', kind:'Project hypothesis', note:'Solar-powered manufacturing linked to housing production. Its modeled economics still need experimental validation.'},
  {id:'rover', title:'Open Source Autonomous Rover', slug:'Open_Source_Autonomous_Rover', kind:'Development proposal', note:'A modular outdoor robot proposal and a pathway toward larger machines and local manufacturing.'},
  {id:'programs', title:'OSE Programs', slug:'OSE_Programs', kind:'Overview / redirects', note:'Redirects to OSE Programs and Offerings. Places machines and institutions within the broader mission.'},
  {id:'cad', title:'Iconic CAD', slug:'Iconic_CAD', kind:'Design vision / in development', note:'Redirects to Iconic CAD Protocol: a shared design language connecting reusable components to fabrication knowledge.'},
  {id:'tutor', title:'OSE Tutor', slug:'OSE_Tutor', kind:'MVP design notes / redirects', note:'A guided workflow that surfaces evidence and missing information, then returns useful contributions to a library.'},
  {id:'crash', title:'Future Builder Crash Course', slug:'Future_Builder_Crash_Course', kind:'Program reading / redirects', note:'Follow the redirects to the Seed Eco-Home Future Builder Crash Course for its learning and building sequence.'},
  {id:'academy', title:'Future Builders Academy', slug:'Future_Builders_Academy', kind:'Education program reading', note:'Production-linked, entrepreneurial and lifelong learning. The wiki links curriculum and application information.'},
  {id:'camping', title:'Camping with Power Tools', slug:'Camping_with_Power_Tools', kind:'Immersive learning format', note:'A camping-based construction-learning experience with practical work, shared meals and teamwork.'},
  {id:'challenge', title:'Collaborative Challenge', slug:'Collaborative_Challenge', kind:'Outline / needs development', note:'Included in the founder’s reading list; the checked page has no substantive program description yet.'},
  {id:'fellowship', title:'Bring Your Own Funding Fellowship', slug:'Bring_Your_Own_Funding_Fellowship', kind:'Link hub / details to confirm', note:'The checked page links to BYOF. Confirm the actual fellowship structure and terms with OSE.'},
  {id:'weekend', title:'A House in a Weekend', slug:'A_House_in_a_Weekend', kind:'Link hub / details to confirm', note:'The checked page points to “1000 Homes in a Day.” The title alone is not evidence of a build-time guarantee.'},
  {id:'rapid', title:'Rapid Learning Tools', slug:'Rapid_Learning_Tools', kind:'Learning tools index', note:'Connects Iconic CAD, OSE Tutor, a Rapid Learning Facility and a 1000 Hour Curriculum.'},
].map(source => ({...source, url:wiki(source.slug)}));

export const chapters = [
  {id:'mission', title:'Start with the possibility', subtitle:'01 / WHY OSE EXISTS', sources:['mission','goals'], paragraphs:[
    'Imagine arriving at a workshop where the drawings are not locked away. You can study a tool, ask why it was made that way, improve it, and leave a record for the next builder. That imagined scene is a useful doorway into Open Source Ecology: knowledge becomes more useful when people can put it to work together.',
    'OSE describes its mission as creating an open-source economy through collaboration. Its concern is larger than making a collection of inexpensive machines. The mission connects access to productive tools with people’s ability to direct their own lives and do meaningful work.',
    'This book begins there, with a question rather than a promise: what would it take for more people to understand, build and improve the systems they depend on? The wiki contains both long-term ambitions and practical experiments. Read them differently. A goal describes a destination; a documented result tells us how far a particular effort has traveled.',
  ], question:'In your own words: what becomes possible when a useful design can be studied, changed and shared?'},
  {id:'people', title:'Build people as well as things', subtitle:'02 / LEARNING AS PARTICIPATION', sources:['change','academy','crash','camping'], paragraphs:[
    'A drawing cannot teach everything on its own. Someone has to learn how to read it, use the tools, notice a problem and work with other people. OSE’s proposed model of change links this human development to the development of practical infrastructure.',
    'The model describes village-scale learning communities that combine education, enterprise and production. Participants would create useful assets as they learn, then carry their knowledge and working methods into further projects. Replication is an ambition to test, not something a diagram alone accomplishes.',
    'The educational entry points have different shapes. Future Builders Academy connects learning with production and entrepreneurship. The crash-course material describes a path through study, practice and housing work. Camping with Power Tools describes a more immersive, camp-based experience of learning through a shared build.',
    'For a newcomer, the important choice is not the most impressive program title. It is the next learning environment that fits your experience, needs and ability to participate. Follow the wiki to the organizers for current arrangements; this reader is not an enrollment calendar or a substitute for supervised tool training.',
  ], question:'What would you like to learn—and what useful thing could you help make while learning it?'},
  {id:'tools', title:'Give knowledge a form people can use', subtitle:'03 / FROM DOCUMENTATION TO DESIGN', sources:['cad','tutor','rapid'], paragraphs:[
    'Shared knowledge needs a usable doorway. A wiki page can preserve context; a drawing can explain geometry; a component library can let a builder reuse a decision instead of starting again. The opportunity is to connect these forms so that an improvement can travel.',
    'Iconic CAD describes a visual design language built around reusable components and their underlying information. The larger vision connects composition, configuration, validation and build documentation. That vision should not be mistaken for a guarantee that every icon in today’s demo is validated or fabrication-ready.',
    'The OSE Tutor design notes add guidance: show the next step, expose the evidence, identify what is missing and help the learner contribute a useful artifact. Rapid Learning Tools gathers related starting points. Together, these ideas frame a learning session as a small contribution to shared knowledge.',
    'You can try that loop here. Arrange cabins in the village tutor, inspect or change a library entry with the FreeCAD learning path, then prepare a documented contribution with the wiki tutor. A saved model is a beginning; clear provenance, limitations and review make it more useful to someone else.',
  ], question:'What would another person need in order to reuse your work without having to ask you everything?'},
  {id:'projects', title:'Make the possibility concrete', subtitle:'04 / A PROPOSED TECHNOLOGY PATH', sources:['solar','rover'], paragraphs:[
    'In the founder’s message that prompted this book, the solar microfactory and autonomous rover were suggested as promising subjects for funding conversations, with an open-source skid steer as a natural next step. That is a strategic invitation, not evidence of secured funding or a completed product.',
    'The solar microfactory page proposes combining solar-powered production, housing work and shared manufacturing infrastructure. It explicitly calls for testing its modeled economics and distinguishing productive capacity from actual sales, value added and profit. A responsible story keeps that distinction visible.',
    'The rover proposal starts with a modular outdoor machine for tasks such as mowing, cultivation and planting. It explores how shared navigation and controls could support different implements, and how learning from a smaller platform might inform a more powerful skid steer. This is a development pathway with safety and field-performance questions still to resolve.',
    'The connection runs in both directions: useful machines can create a reason to develop manufacturing capacity, while a microfactory could help produce those machines. The following reading map is a proposed relationship—not a claim that these stages are built, sequentially funded or ready for autonomous operation.',
  ], ladder:[['01 / LEARN AT SMALL SCALE','Autonomous rover','Explore a modular platform and demonstrate useful, supervised field performance.'],['02 / DEVELOP MORE CAPABILITY','Open-source skid steer','Investigate how proven concepts could transfer to heavier work; new risks require new validation.'],['03 / SUPPORT PRODUCTION','Solar microfactory','Test the infrastructure and economics for making useful products and more of their components.']], question:'What evidence would make this proposal credible: a field test, a reproducible design, a safety review, a measured production run?'},
  {id:'replication', title:'Share the whole way of working', subtitle:'05 / THE PHILANTHROPIC FRANCHISE', sources:['franchise','programs'], paragraphs:[
    'If one workshop succeeds, how does another community benefit? Sending a machine is one answer. Sharing the knowledge of how to teach, organize, produce and sustain the work is a larger one.',
    'The Philanthropic Franchise page describes a proposed network of locally adapted campuses. Research, education, development and production would work together; productive surplus would support further public-purpose activity. A mature node would help other autonomous nodes develop while sharing improvements across the network.',
    'Here, “franchise” describes an ambition to make an entire mission-driven institution replicable, not merely to distribute a branded product. It is not an offer of a commercial franchise or a promise that a campus already supports itself. The wiki marks this page as OSE Canon; that tag describes its place in OSE’s framing, not experimental proof of the model.',
    'The programs overview widens the story from machines to institutions. A coherent introduction can help someone see how a course, a tool library and a production project might support the same mission. Demonstrating that connection in practice remains the work.',
  ], question:'Beyond blueprints, what would a second team need to reproduce a project responsibly?'},
  {id:'invitation', title:'Leave room for the next person', subtitle:'06 / FROM ALIGNMENT TO AN INVITATION', sources:['challenge','fellowship','weekend','rapid'], paragraphs:[
    'A good introduction does not ask everyone to do the same thing. One person may want a place to learn. Another may be able to review a design, document a result, organize a team or support a carefully bounded experiment. Tell enough of the story for someone to recognize a role, then offer a concrete next conversation.',
    'The founder’s reading list also names Collaborative Challenge, Bring Your Own Funding Fellowship and A House in a Weekend. At the time of this edition, those pages were outlines or short pointers rather than complete program explanations. They belong on the reading trail, but this book does not invent schedules, eligibility, deliverables or funding terms for them.',
    'For a recruiting conversation, describe the work and the support a person would need to contribute. For a funding conversation, distinguish what exists from what is proposed, name an experiment and ask what evidence should determine the next decision. Do not turn a modeled outcome into a promised return.',
    'Use the writing workspace below to make a short invitation in your own voice. Keep the source close to the claim and the uncertainty close to the proposal. The next chapter of this story should be something people can help verify and improve—not only something they are asked to believe.',
  ], question:'Who is your reader, what can you honestly show them, and what is one useful next step?'},
];

export const audiencePrompts = {
  collaborator:'Name a bounded task, the existing evidence and the skills or review it needs. Invite a conversation; do not imply an assigned role or an open vacancy.',
  learner:'Start with a question they care about and a realistic first learning step. Link the program source and ask them to confirm current arrangements with the organizers.',
  supporter:'Separate the demonstrated work from the proposed experiment. Name what needs validation and the next discussion; do not invent budgets, commitments or financial returns.',
};
export function bookMarkdown() {
  return '# Mini OSE Book\n## The things we can build together\n\nEditorial draft 01 · September 12, 2026\n\nA source-linked introduction, not an official canon declaration. Project proposals are not completed products or funding commitments.\n\n' + chapters.map(ch => `## ${ch.subtitle}: ${ch.title}\n\n${ch.paragraphs.join('\n\n')}\n\n${ch.ladder ? ch.ladder.map(x => `- ${x[1]}: ${x[2]}`).join('\n') + '\n\n' : ''}Reflection: ${ch.question}\n\nSources:\n${ch.sources.map(id => {const s = sources.find(s => s.id === id); return `- [${s.title}](${s.url})`;}).join('\n')}`).join('\n\n') + '\n\n## Wiki reading trail\n\n' + sources.map(s => `- [${s.title}](${s.url}) — ${s.kind}. ${s.note}`).join('\n') + '\n\nLive OSE Canon category: https://wiki.opensourceecology.org/wiki/Category:OSE_Canon\n\nOriginal editorial connective writing and paraphrased OSE wiki material; wiki contributors credited through source links. Book text: CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/). Source pages may carry additional notices.\n\nDesigned by GoodAncestor Foundation — https://www.goodancestor.com\n';
}
