const wikiSources = [
  ['OSE wiki', 'https://wiki.opensourceecology.org/wiki/Main_Page'],
  ['Wikibot · access may be restricted or unavailable', 'https://wikibot.goodancestor.com/'],
  ['Wikibot review room · sign-in may be required', 'https://wikibot.goodancestor.com/review'],
  ['VCS contribution guide', 'https://github.com/OpenSourceEcology/vcs-library/blob/main/CONTRIBUTING.md'],
  ['VCS ownership & provenance', 'https://github.com/OpenSourceEcology/vcs-library/blob/main/GOVERNANCE.md'],
];
const cadSources = [
  ['Workbench installation & usage', 'https://github.com/OpenSourceEcology/ose-library-workbench'],
  ['Editable VCS library', 'https://github.com/OpenSourceEcology/vcs-library'],
  ['Browse rendered library entries', 'https://opensourceecology.github.io/ose-library-site/'],
];
export const tracks = {
  wiki: {
    title: 'Turn what you learn into shared knowledge.',
    intro: 'Care for a wiki page, review a bot’s suggestion, and prepare your own design for community review.',
    sources: wikiSources,
    steps: [
      { title: 'Make one careful manual edit', html: `<p>Start small: choose one page you understand and one improvement you can verify.</p><ol><li>Read the page and its history. Follow the source links. Check whether someone is already discussing the change.</li><li>Sign in to the OSE wiki and open Edit (or Edit source). For practice, use a personal sandbox rather than overwriting a shared design page.</li><li>Fix a heading, typo or explanation. Preserve technical numbers, units, links, templates, categories and attribution unless you have evidence for changing them.</li><li>Use Preview and review the changes. Add a specific edit summary, save when ready, then inspect the saved revision. If an edit conflict appears, merge against the latest text.</li></ol>`, question: 'A page says “wall height: 2.4 m.” A cleanup changes it to 2.7 m without a source. What should you do?', options: ['Keep the new number because it reads better', 'Preserve 2.4 m and flag the unsupported change', 'Remove all dimensions'], correct: 1, explanation: 'Cleanup is not design revision. Preserve the documented value until a source supports changing it.', help: [['What is a useful edit summary?', 'Be specific: “Correct heading levels; retain dimensions and source links.” It helps the next editor understand the scope.'], ['Can I upload any CAD file?', 'Check the wiki’s upload permissions and allowed formats. If a format is not supported, link to a stable public source repository or file location. Confirm redistribution rights first.']] },
      { title: 'Give wikibot a bounded task', html: `<p>Wikibot drafts changes for human review. It is not a license to rewrite the wiki unattended. The public service may require access; this tutorial works even when it is offline.</p><ol><li>Choose a page title and a narrow purpose. Use “Suggest a page for the bot” when available; operators can use “Run a mission” to draft proposals.</li><li>Match the mission to the job: <code>improve-article</code> for clarity and formatting, <code>categorize</code> for uncategorized pages, or <code>dead-links</code> for link maintenance. The specialized <code>wiki-map-update</code> is not a general cleanup mission.</li><li>Read the environment banner and destination before doing anything. The review-server test workflow promotes to a local wiki copy; production publishing is a separate permissioned action.</li><li>Open the review queue and inspect the proposed diff. A suggestion or mission run is not an approved edit.</li></ol>`, question: 'You want clearer headings while preserving the article’s facts. Which mission fits?', options: ['improve-article', 'wiki-map-update', 'Approve every pending proposal'], correct: 0, explanation: 'improve-article is intended for formatting, grammar and structure while preserving facts and wiki markup.', help: [['The bot page does not open', 'Use the manual-edit path or prepare a draft here. Ask the wikibot operator for current access. Never paste account passwords or reviewer credentials into this tutor.'], ['What do I put in a suggestion?', 'Use the exact page title and a narrow, verifiable concern. Check the resulting proposal rather than assuming the bot understood your intent.']] },
      { title: 'Practice reviewing a proposal', html: `<p><strong>Practice fixture — not a real wiki edit.</strong> Compare these snippets:</p><pre>BEFORE\n== Cabin ==\nTwo stories; width 13 ft.\nSource: [[Cabin drawings]]\n\nPROPOSED\n== Two-story cabin ==\nWidth 12 ft. Ready for construction.</pre><p>Look for changed measurements, missing sources and newly asserted safety claims. In the real review queue, an authorized reviewer can edit the proposed wikitext, approve or reject it. Reject or correct unsupported changes before approval.</p><p>If the source page has changed, review a fresh proposal against the current revision. After an authorized promotion, verify the destination and resulting revision or receipt. “Approved” is not proof that the live wiki changed.</p>`, question: 'What is the right review decision for this proposed edit?', options: ['Approve: the new title is clearer', 'Approve, then check the dimensions later', 'Reject or correct: altered width, lost source, unsupported readiness claim'], correct: 2, explanation: 'All three substantive changes need attention. A better heading does not compensate for lost evidence or an invented construction claim.', help: [['When is an edit really published?', 'Only after the authorized publishing action succeeds at the intended destination and you verify its resulting revision. A test-copy promotion is not a production edit.'], ['How do I review a broken link?', 'Open the original and proposed replacement. A temporary failure does not prove a source is gone. Preserve attribution and verify that replacement content supports the same claim.']] },
      { title: 'Prepare a wiki design page', html: `<p>Use the contribution workspace below to record your design, editable files, dimensions, attribution, license, validation and unresolved questions. Unknown is better than invented.</p><p>The builder creates a wikitext starter. Search the wiki for the design first. If it exists, merge your contribution into the appropriate section; do not paste a whole replacement over someone else’s page. Otherwise choose a clear title, preview the new page, and save it yourself with an edit summary.</p><p>Include a stable revision or version in your source description. Keep the original author and source license with derived files. A file being downloadable does not establish permission to redistribute it.</p>`, checklist: 'I understand this produces a draft; I will verify sources, licensing and the target page before saving.', help: [['Can I submit the two-story cabin?', 'You can prepare its documentation for review. The imported cabin source records “All rights reserved”; do not relabel it as open-licensed. Resolve redistribution permissions and preserve its source attribution.'], ['What should the page include?', 'Explain what the design does, link editable source files, state units and interfaces, describe what was actually tested, and list unresolved limitations. Separate source facts from your proposed changes.']] },
      { title: 'Request VCS inclusion for review', html: `<p>Use the same workspace to prepare a Markdown review request. “Open GitHub review form” opens an unsubmitted issue in <code>OpenSourceEcology/vcs-library</code>. You choose whether to send it. An issue asks for discussion; it does not publish a library entry or unlock an icon.</p><ol><li>Check existing entries and issues for duplicates. For an existing entry, consult its <code>meta.yaml</code> owner.</li><li>For an implementation contribution, follow the contribution guide: an entry needs <code>schema.py</code>, <code>compiler.py</code>, <code>meta.yaml</code> and <code>expect.yaml</code>. Start from a suitable entry in the same layer. Match its directory and metadata ID.</li><li>Run code and output validation, inspect the reports, and document limitations. Output checks require FreeCAD. A WIP failure can return exit code zero: inspect the report, not only the exit status.</li><li>Open a pull request for the implementation and let the owner / maintainers review it. Keep provenance and licensing evidence attached.</li></ol>`, question: 'Your request has been submitted. Is the design now a validated, selectable VCS icon?', options: ['Yes, submitting the issue installs it', 'No, inclusion and integration still need review'], correct: 1, explanation: 'Discussion, implementation, validation, maintainer acceptance and tutor integration are distinct steps.', help: [['What should I attach?', 'Public editable CAD/source links, screenshots or drawings, dimensions and interfaces, author/license evidence, validation reports and specific review questions. Do not claim fabrication readiness based on a successful compile.'], ['I do not write compilers yet', 'Submit a clearly labeled request for review with the design evidence you have. Ask which existing entry or layer is appropriate; do not present the request as a completed Schema Canon implementation.']] },
    ],
  },
  freecad: {
    title: 'From a CAD model to a reusable building block.',
    intro: 'A guided companion to FreeCAD and the OSE Library Workbench. Keep this page beside FreeCAD while you work.',
    sources: cadSources,
    steps: [
      { title: 'Get comfortable in FreeCAD', html: `<p>Use FreeCAD 1.x. Start with a copy of a model, not your only original.</p><ol><li>Open an FCStd document. Find the model tree, property panel and 3D view. Select an object in the tree and inspect its properties.</li><li>Use the View menu to fit the model and try standard views. Mouse navigation depends on your configured navigation style; check it before practicing pan, orbit and zoom.</li><li>Distinguish selecting an object from editing its dimensions. Avoid moving geometry accidentally while learning the view controls.</li><li>Save a separate working FCStd file. Keep source files and their author/license information together.</li></ol><p>Try selecting one object, fitting the model and returning to an overall view before continuing.</p>`, checklist: 'I can identify the active document, select an object and return to a useful view.', help: [['My mouse gestures are different', 'FreeCAD supports different navigation styles. Check the active style and its controls in FreeCAD instead of assuming browser-viewer gestures apply.'], ['Can the tutor control my FreeCAD?', 'No. This path provides instructions and checks. Run the desktop commands yourself; the static website does not connect to your desktop.']] },
      { title: 'Install the assistance tools', html: `<p>The OSE Library Workbench is currently a manual installation, not an Addon Manager registry install.</p><ol><li>Open FreeCAD’s Python console and run <code>App.getUserAppDataDir()</code>. Clone <a href="https://github.com/OpenSourceEcology/ose-library-workbench">ose-library-workbench</a> into <code>Mod/ose-library-workbench</code> beneath that directory, then restart FreeCAD.</li><li>Make <code>libtools</code> and <code>yaml</code> available to FreeCAD’s Python interpreter. In a shared Python environment, the README gives the pip command below. A bundled FreeCAD may use a different interpreter from your terminal: follow its environment setup, not a guessed Python path.</li><li>In the FreeCAD console, verify <code>import libtools, yaml</code>. Clone <a href="https://github.com/OpenSourceEcology/vcs-library">vcs-library</a> separately for editable entries.</li><li>Select the <strong>OSE Library</strong> workbench. Only compile trusted source: entry compilers execute Python.</li></ol><pre>python -m pip install 'libtools @ git+https://github.com/OpenSourceEcology/vcs-library'</pre>`, question: 'pip worked in your terminal, but FreeCAD cannot import libtools. What should you check?', options: ['Whether the package is available in FreeCAD’s own Python environment', 'Whether the model is zoomed in', 'Whether the wiki page has a category'], correct: 0, explanation: 'The terminal and bundled FreeCAD can use different interpreters. Verify imports inside FreeCAD.', help: [['The workbench is missing', 'Check that InitGui.py is inside Mod/ose-library-workbench under the user application directory returned by FreeCAD, then restart. Inspect FreeCAD’s Report view for import errors.'], ['Can a checkout supply libtools?', 'The workbench README also supports adding the absolute vcs-library checkout directory to sys.path in the FreeCAD console. PyYAML must still be available there. Consult the linked installation instructions for your environment.']] },
      { title: 'Open a library and compile', html: `<ol><li>Choose <strong>Open Library</strong>. Select the <code>vcs-library</code> checkout for housing entries, or its current <code>collections/gvcs</code> directory for machine entries. These are storage locations; use the actual library root if reorganized.</li><li>Select an entry and inspect its source and purpose. Choose <strong>Compile Entry</strong> to create its document.</li><li>Keep the matching entry selected and the new document active. Fit the model and inspect what was generated.</li><li>Save a working FCStd document. Its binding records the library location, entry identity and managed objects.</li></ol><p>For your first exercise, compile an existing entry before attempting a new one. Browse rendered entries through the resource link if you do not have FreeCAD installed yet.</p>`, question: 'You compiled entry A but have an unrelated document active. What should you do before editing parameters?', options: ['Use the unrelated document anyway', 'Activate A’s bound document and select entry A'], correct: 1, explanation: 'The workbench checks the selected entry and document binding to avoid editing the wrong model.', help: [['Why does it reject my document?', 'Select the same entry and the document compiled from that checkout. An unrelated document, different entry or different checkout is intentionally rejected.'], ['My library checkout moved', 'If the saved source location no longer matches, compile a new document from the selected entry. Keep the old FCStd as a reference; do not force an unrelated binding.']] },
      { title: 'Change one exposed parameter', html: `<ol><li>With the correct entry and document active, choose <strong>Edit Parameters</strong>.</li><li>Record the original value. Change one exposed dimension, keeping the shown units. Source identity, units and source-part lists are read-only; not every imported dimension is adjustable.</li><li>Choose <strong>Apply</strong> and inspect the geometry. Successful application replaces the entry’s managed objects and preserves unrelated objects. A failed compile rolls back geometry and parameters.</li><li>Compare the result with your intent, then save your working document. Do not interpret fixed source geometry as a fully parametric model.</li></ol>`, question: 'You changed a form value and exported schema, but did not Apply. Has the document geometry changed?', options: ['Yes, exporting always rebuilds geometry', 'No, Apply is the geometry-changing step'], correct: 1, explanation: 'Export writes a proposed schema file. Apply performs the compile that changes managed geometry.', help: [['A dimension cannot be edited', 'Only fields exposed by the entry schema are editable. Fixed imported source geometry is not made parametric by the workbench. A deeper change requires source/entry authoring.'], ['Apply failed', 'Read the reported error and check the changed value and units. The managed edit workflow retains the previous successful geometry and parameters on compile failure. Try a valid value; do not infer success from the unchanged model.']] },
      { title: 'Validate, export and contribute', html: `<ol><li>Choose <strong>Validate Entry</strong> with the matching document active. Inspect both code and geometry findings in the panel and <code>&lt;library-root&gt;/reports/</code>.</li><li>Choose <strong>Export changed schema…</strong>. Review the resulting <code>schema.py.new</code> beside <code>schema.py</code>; manually merge only the intended changes into a source branch. Export does not merge or publish automatically.</li><li>Recompile and validate the merged source. Preserve your FCStd, attribution and exact source revision; document unresolved fit or assembly findings.</li><li>Use the <a href="learn.html?track=wiki&step=4">wiki & VCS contribution path</a> to prepare a review request, then follow the library’s contribution guide for a pull request.</li></ol><p>A compile or validation pass is not engineering approval or proof of fabrication readiness.</p>`, question: 'Your entry compiles, but the validation report lists an unresolved fit finding. How should you share it?', options: ['Call it fabrication-ready', 'Include the finding and request the relevant review'], correct: 1, explanation: 'Share the evidence and limitations honestly. Review findings do not disappear because geometry compiled.', help: [['What does schema.py.new do?', 'It is a reviewable proposed schema file. It does not overwrite schema.py, apply geometry changes or open a pull request. Review and merge it yourself.'], ['How do I make a brand-new entry?', 'The workbench currently supports editing existing entries; GUI scaffolding is future work. Follow vcs-library’s contribution guide and start from a suitable existing entry with schema.py, compiler.py, meta.yaml and expect.yaml.']] },
    ],
  },
};
