"""Reusable geometry builders for SEH wall library entries.

Framing-lumber positions (studs, plates, kings, jacks, headers, cripples,
sills, blocking) are NOT computed here. They come from
web/assets/lib/members.json, generated by `node scripts/export_members.mjs`
from `enumerateMembers()` in web/js/members.js — the single source for that
math (design_decisions.md Decision 6). This module turns that member list
into FreeCAD box shapes; it does not re-derive stud/cripple positions.

Sheathing (OSB) is the one exception, kept deliberately UN-consolidated: the
JS side models OSB as several rectangular "strips" split around a rough
opening (see enumerateAperture's sheathing members), while this module still
cuts a single full sheet with a rectangular hole. That is a real, pre-existing
geometry difference between the two implementations (tracked as CAD-AUD-005
in docs/audits and recorded as a `known_issue` in each aperture module's
meta.yaml) — this refactor does not silently pick a winner between them, so
OSB generation here is untouched and members.json's 'sheathing' role entries
are ignored by `boxes_from_members`.
"""

import json
import os

IN_TO_MM = 25.4
PORT_SIZE = 1.0  # mm, tiny marker cube

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEMBERS_PATH = os.path.join(_REPO_ROOT, "web", "assets", "lib", "members.json")

_members_cache = None


def _load_members_doc():
    global _members_cache
    if _members_cache is None:
        with open(MEMBERS_PATH) as f:
            _members_cache = json.load(f)
    return _members_cache


def members_for(instance_id):
    """Return the enumerateMembers() member list for a module id.

    Raises KeyError with a clear message if the module isn't in the
    committed members.json (i.e. `node scripts/export_members.mjs` needs to
    be re-run after adding a module).
    """
    doc = _load_members_doc()
    try:
        return doc[instance_id]
    except KeyError:
        raise KeyError(
            f"{instance_id!r} not found in {MEMBERS_PATH} — "
            "run `node scripts/export_members.mjs` after adding/renaming a module."
        )


def _member_object_name(role, index, total):
    """Reproduce the pre-refactor FreeCAD object-naming convention.

    library/modules/*/expect.yaml (validated by `libtools validate-output`)
    matches solid names against role-name *patterns* such as `king_stud_*`
    and `jack_stud_*` — that naming predates this refactor and is a contract
    with library entry validation, not just cosmetic, so it's preserved
    verbatim rather than replaced with the member list's own role strings.
    """
    if role == "king":
        return "king_stud_left" if index == 0 else "king_stud_right"
    if role == "jack":
        return "jack_stud_left" if index == 0 else "jack_stud_right"
    if role == "bottom_plate":
        if total == 1:
            return "bottom_plate"
        return "bottom_plate_left" if index == 0 else "bottom_plate_right"
    if role == "top_plate":
        if total == 1:
            return "top_plate"
        return f"top_plate_{index + 1}"
    if role == "stud":
        return f"stud_{index + 1}"
    if role == "top_cripple":
        return f"top_cripple_{index + 1}"
    if role == "lower_cripple":
        return f"lower_cripple_{index + 1}"
    if role == "sill_block":
        return f"blocking_{index + 1}"
    # header, sill, subheader: one per panel, no suffix.
    return role


def boxes_from_members(members, depth_mm):
    """Turn a members.json member list into (name, sx,sy,sz, px,py,pz) box specs.

    Pure Python, no FreeCAD import — testable without FreeCAD (see
    tests/test_members_boxes.py). Skips 'sheathing' members; see the module
    docstring for why OSB stays separately generated.

    Coordinate convention matches the existing canonical south-facing pose:
    x_mm/z_mm/w_mm/h_mm from the member list map straight onto box
    width/height (px,sx / pz,sz); the panel depth axis (sy/py) is not part of
    the member list (it is panel-local 2D) and is supplied by the caller.
    """
    by_role = {}
    for m in members:
        if m["role"] == "sheathing":
            continue
        by_role.setdefault(m["role"], []).append(m)

    boxes = []
    for role, group in by_role.items():
        total = len(group)
        for index, m in enumerate(group):
            name = _member_object_name(role, index, total)
            boxes.append((name, m["w_mm"], depth_mm, m["h_mm"], m["x_mm"], 0.0, m["z_mm"]))
    return boxes


def nominal_to_actual(nominal):
    """Return (thickness_in, depth_in) for nominal lumber size."""
    table = {
        "2x2": (1.5, 1.5),
        "2x3": (1.5, 2.5),
        "2x4": (1.5, 3.5),
        "2x6": (1.5, 5.5),
        "2x8": (1.5, 7.25),
        "2x10": (1.5, 9.25),
        "2x12": (1.5, 11.25),
    }
    return table[nominal]


def in_mm(v):
    return v * IN_TO_MM


def ft_in(v):
    return v * 12.0


def stud_positions(width_in, stud_thick_in, spacing_oc_in):
    """Compute stud X positions (in inches) including end studs."""
    pos = [0.0]
    right_edge = width_in - stud_thick_in
    cur = spacing_oc_in
    while cur + stud_thick_in <= right_edge:
        pos.append(cur)
        cur += spacing_oc_in
    if pos[-1] != right_edge:
        pos.append(right_edge)
    return pos


def cripple_x_positions(width_in, st_in, spacing_in, lo_in, hi_in):
    """OC-grid stud X positions (inches) that fall inside the opening."""
    xs = [
        x
        for x in stud_positions(width_in, st_in, spacing_in)
        if lo_in < x and x + st_in < hi_in
    ]
    if not xs:
        xs = [(lo_in + hi_in) / 2.0 - st_in / 2.0]
    return xs


def build_wall_document(instance):
    import FreeCAD

    doc = FreeCAD.newDocument(instance["id"])
    build_instance_into_doc(instance, doc, compound=True)
    doc.recompute()
    return doc


def build_wall(instance):
    return build_wall_document(instance)


def build_aperture_panel(instance):
    return build_wall_document(instance)


def build_instance_into_doc(instance, doc, compound=False):
    if "aperture" in instance["parameters"]:
        return _build_aperture_into_doc(instance, doc, compound=compound)
    return _build_plain_wall_into_doc(instance, doc, compound=compound)


def build_framed_wall_panel(instance, doc, compound=False):
    return _build_plain_wall_into_doc(instance, doc, compound=compound)


def build_interior_wall_panel(instance, doc, compound=False):
    return _build_plain_wall_into_doc(instance, doc, compound=compound)


def build_aperture_wall_panel(instance, doc, compound=False):
    return _build_aperture_into_doc(instance, doc, compound=compound)


def instance_from_schema(schema):
    return {
        "id": schema["document_name"],
        "family": schema["family"],
        "parameters": _pairs_to_dict(schema["parameters"]),
    }


def _pairs_to_dict(value):
    if isinstance(value, tuple):
        return {key: _pairs_to_dict(child) for key, child in value}
    return value


def _add_shape(doc, name, shape):
    obj = doc.addObject("Part::Feature", name)
    obj.Label = name
    obj.Shape = shape
    return obj


def _box_shape(sx, sy, sz, px=0, py=0, pz=0):
    import FreeCAD
    import Part

    shape = Part.makeBox(sx, sy, sz)
    shape.translate(FreeCAD.Vector(px, py, pz))
    return shape


def _emit_shapes(doc, named_shapes, compound):
    import Part

    if compound:
        wall = Part.makeCompound([shape for _, shape in named_shapes])
        _add_shape(doc, "wall_module", wall)
        return [doc.Objects[-1]]

    objects = []
    for name, shape in named_shapes:
        objects.append(_add_shape(doc, name, shape))
    return objects


def _add_ports(doc, W, osb):
    half = PORT_SIZE / 2.0
    port_y = -osb if osb > 0 else 0
    left = _box_shape(PORT_SIZE, PORT_SIZE, PORT_SIZE, -half, port_y - half, -half)
    right = _box_shape(PORT_SIZE, PORT_SIZE, PORT_SIZE, W - half, port_y - half, -half)
    return [_add_shape(doc, "port_left", left), _add_shape(doc, "port_right", right)]


def _build_plain_wall_into_doc(instance, doc, compound):
    p = instance["parameters"]

    width_in = ft_in(p["nominal_width_ft"])
    height_in = ft_in(p["nominal_height_ft"])
    _stud_thick_in, stud_depth_in = nominal_to_actual(p["stud_lumber_nominal"])
    osb_thick_in = p["osb_thickness_in"]

    W = in_mm(width_in)
    H = in_mm(height_in)
    sd = in_mm(stud_depth_in)
    osb = in_mm(osb_thick_in)

    members = members_for(instance["id"])
    shapes = [
        (name, _box_shape(sx, sy, sz, px, py, pz))
        for name, sx, sy, sz, px, py, pz in boxes_from_members(members, sd)
    ]

    if osb_thick_in > 0:
        shapes.append(("osb_panel", _box_shape(W, osb, H, 0, -osb, 0)))

    objects = _emit_shapes(doc, shapes, compound=compound)
    objects.extend(_add_ports(doc, W, osb))
    doc.recompute()
    return objects


def _build_aperture_into_doc(instance, doc, compound):
    import FreeCAD
    import Part

    p = instance["parameters"]
    a = p["aperture"]

    width_in = ft_in(p["nominal_width_ft"])
    height_in = ft_in(p["nominal_height_ft"])
    _st_in, sd_in = nominal_to_actual(p["stud_lumber_nominal"])
    osb_thick_in = p["osb_thickness_in"]

    ro_w_in = a["rough_opening_width_in"]
    ro_h_in = a["rough_opening_height_in"]
    sill_top_in = a.get("sill_height_in", 0) or 0

    W = in_mm(width_in)
    H = in_mm(height_in)
    sd = in_mm(sd_in)
    osb = in_mm(osb_thick_in)

    # Only needed for the OSB cut region (see module docstring — OSB stays
    # separately generated) and the port markers.
    ro_w = in_mm(ro_w_in)
    ro_x0 = (W - ro_w) / 2.0
    ro_z_bottom = in_mm(sill_top_in)
    ro_z_top = ro_z_bottom + in_mm(ro_h_in)

    members = members_for(instance["id"])
    shapes = [
        (name, _box_shape(sx, sy, sz, px, py, pz))
        for name, sx, sy, sz, px, py, pz in boxes_from_members(members, sd)
    ]

    if osb_thick_in > 0:
        osb_panel = Part.makeBox(W, osb, H)
        osb_panel.translate(FreeCAD.Vector(0, -osb, 0))
        hole = Part.makeBox(ro_w, osb + 2, ro_z_top - ro_z_bottom)
        hole.translate(FreeCAD.Vector(ro_x0, -osb - 1, ro_z_bottom))
        shapes.append(("osb_panel", osb_panel.cut(hole)))

    objects = _emit_shapes(doc, shapes, compound=compound)
    objects.extend(_add_ports(doc, W, osb))
    doc.recompute()
    return objects
