// Run against the real local service. Both variants are generated by FreeCAD.
import { chromium } from "playwright";
import assert from "node:assert/strict";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
const base = process.env.STUDIO_URL || "http://127.0.0.1:8766";
const output = resolve(
  process.env.STUDIO_VERIFY_OUT || "reports/studio-browser",
);
await mkdir(output, { recursive: true });
const browser = await chromium.launch({
  headless: true,
  args: ["--use-angle=swiftshader", "--enable-webgl"],
});
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } }),
  errors = [];
page.on("pageerror", (e) => errors.push(e.message));
const save = async (id, name) => {
  const pending = page.waitForEvent("download");
  await page.locator("#" + id).click();
  const d = await pending;
  await d.saveAs(resolve(output, name));
  return resolve(output, name);
};
try {
  await page.goto(base + "/studio.html");
  await page.waitForFunction(
    () => document.querySelector("#viewport").dataset.previewState === "ready",
  );
  await page.waitForFunction(
    () =>
      document.querySelector("#generation-status").textContent ===
      "FreeCAD connected",
  );
  await page.locator("#chat-input").fill("Show machine parts");
  await page.locator("#send-chat").click();
  assert.equal(
    await page.locator("#palette-title").textContent(),
    "Machine parts",
  );
  await page.locator("#chat-input").fill("Show housing modules");
  await page.locator("#send-chat").click();
  assert.equal(
    await page.locator("#palette-title").textContent(),
    "Housing library",
  );
  for (const domain of ["house", "machines"]) {
    await page.locator(`[data-domain="${domain}"]`).click();
    assert.equal(
      await page.locator("#instance-count").textContent(),
      domain === "house" ? "12 placed modules" : "3 placed modules",
    );
    await page.screenshot({
      path: resolve(output, domain + "-start.png"),
      fullPage: true,
    });
    await page.locator("#lesson-action").click();
    const param = domain === "house" ? "opening_width_in" : "width_mm";
    await page.locator("#lesson-action").click();
    await page.waitForFunction(
      () =>
        document.querySelector("#comparison-viewport").dataset.previewState ===
        "comparison",
      null,
      { timeout: 115000 },
    );
    assert.equal(
      await page.locator("#save-draft").isDisabled(),
      true,
      "generation is not a review acknowledgement",
    );
    await page.screenshot({
      path: resolve(output, domain + "-compare.png"),
      fullPage: true,
    });
    await page.locator("#review-candidate").click();
    assert(
      await page
        .locator("#review-content")
        .textContent()
        .then((t) => t.includes("Still unreviewed")),
    );
    await page.locator("#ack-review").click();
    await page
      .locator("#draft-name")
      .fill(domain === "house" ? "My 30 inch window" : "My 90 mm plate");
    await page.locator("#save-draft").click();
    assert.equal(await page.locator("#asset-palette button").count(), 4);
    await page.locator("#lesson-action").click();
    assert.equal(
      await page.locator("#step-label").textContent(),
      "LESSON COMPLETE",
    );
    const projectPath = await save("save-project", domain + ".json");
    const doc = JSON.parse(await readFile(projectPath, "utf8"));
    const variant = doc.assets.find((a) => a.draft);
    assert.equal(variant.parameters[param], domain === "house" ? 30 : 90);
    assert(doc.instances.some((i) => i.asset_id === variant.id));
    await save("export-cad", domain + ".FCStd");
    await save("export-contribution", domain + "-contribution.zip");
    await page.locator("#tab-plan").click();
    await save("export-svg", domain + ".svg");
    await page.screenshot({
      path: resolve(output, domain + "-plan.png"),
      fullPage: true,
    });
    const originalRotation = doc.instances.find(
      (i) => i.asset_id === variant.id,
    ).rotation[2];
    await page.locator("#rotate").click();
    await page.locator("#undo").click();
    const undo = JSON.parse(
      await readFile(await save("save-project", domain + "-undo.json"), "utf8"),
    );
    assert.equal(
      undo.instances.find((i) => i.asset_id === variant.id).rotation[2],
      originalRotation,
    );
    await page.locator("#project-file").setInputFiles({
      name: "invalid.json",
      mimeType: "application/json",
      buffer: Buffer.from(
        '{"format":"ose-composition-studio","version":1,"domain":"house","assets":[],"instances":[{}]}',
      ),
    });
    await page.waitForFunction(() =>
      document
        .querySelector("#notice")
        .textContent.startsWith("Could not open project"),
    );
    const preserved = JSON.parse(
      await readFile(
        await save("save-project", domain + "-preserved.json"),
        "utf8",
      ),
    );
    assert.deepEqual(preserved, undo);
    await page.locator("#project-file").setInputFiles(projectPath);
    await page.waitForFunction(() =>
      document
        .querySelector("#notice")
        .textContent.startsWith("Opened the project"),
    );
    // An unavailable generation service must preserve the saved design.
    await page.locator("#tab-3d").click();
    if (domain === "machines") {
      await page
        .locator("#asset-palette button")
        .filter({ hasText: "My 90 mm plate" })
        .click();
      await page.locator("#param-width_mm").fill("100");
      await page.route("**/api/studio/generate", (route) =>
        route.fulfill({
          status: 503,
          json: { error: "Generation service unavailable (test)" },
        }),
      );
      await page.locator("#generate").click();
      await page.waitForFunction(() =>
        document
          .querySelector("#generation-status")
          .textContent.includes("preserved"),
      );
      const after = JSON.parse(
        await readFile(
          await save("save-project", "after-failed-generation.json"),
          "utf8",
        ),
      );
      assert.deepEqual(after, doc);
      await page.unroute("**/api/studio/generate");
    }
    await page.reload();
    await page.waitForFunction(
      () =>
        document.querySelector("#viewport").dataset.previewState === "ready",
    );
    if (domain === "machines")
      await page.locator('[data-domain="machines"]').click();
    assert.equal(
      await page.locator("#asset-palette button").count(),
      4,
      "draft restored after reload",
    );
  }
  // Optional live model verification uses the real configured service.
  if ((await page.locator("#tutor-mode").textContent()).includes("Local AI")) {
    await page
      .locator("#asset-palette button")
      .filter({ hasText: "My 90 mm plate" })
      .click();
    await page
      .locator("#chat-input")
      .fill(
        "Please propose 100 mm width, keeping the current height and thickness.",
      );
    await page.locator("#send-chat").click();
    await page.waitForFunction(
      () => document.querySelector("#param-width_mm")?.value === "100",
      null,
      { timeout: 60000 },
    );
    const after = JSON.parse(
      await readFile(
        await save("save-project", "after-tutor-proposal.json"),
        "utf8",
      ),
    );
    assert.equal(
      after.assets.find((a) => a.draft).parameters.width_mm,
      90,
      "a tutor proposal does not mutate geometry",
    );
  }
  // Diagram annotations survive project serialization and SVG export. They
  // remain separate from CAD placements and engineering interfaces.
  await page.locator("#tab-plan").click();
  await page.locator("#annotation-text").fill("Review mounting holes");
  await page.locator("#add-note").click();
  await page.locator("#plan").click({ position: { x: 60, y: 50 } });
  await page.locator("#add-arrow").click();
  await page.locator("#plan").click({ position: { x: 80, y: 70 } });
  await page.locator("#plan").click({ position: { x: 160, y: 140 } });
  const annotated = JSON.parse(
    await readFile(await save("save-project", "annotated.json"), "utf8"),
  );
  assert.equal(annotated.annotations.length, 2);
  assert.equal(annotated.annotations[0].text, "Review mounting holes");
  const diagram = await readFile(
    await save("export-svg", "annotated.svg"),
    "utf8",
  );
  assert(
    diagram.includes("Review mounting holes") && diagram.includes("marker-end"),
  );
  await page.locator("#clear-notes").click();
  await page.locator("#undo").click();
  const restored = JSON.parse(
    await readFile(await save("save-project", "annotations-undo.json"), "utf8"),
  );
  assert.deepEqual(restored.annotations, annotated.annotations);
  await page.locator("#tab-3d").click();
  await page.waitForFunction(
    () => document.querySelector("#notice").textContent === "",
  );
  for (const width of [390, 768]) {
    await page.setViewportSize({ width, height: 900 });
    await page.screenshot({
      path: resolve(output, `responsive-${width}.png`),
      fullPage: true,
    });
    assert.equal(
      await page.evaluate(
        () => document.documentElement.scrollWidth > innerWidth,
      ),
      false,
      "no horizontal overflow",
    );
  }
  assert.deepEqual(errors, []);
  await writeFile(
    resolve(output, "receipt.json"),
    JSON.stringify(
      {
        passed: true,
        journeys: ["house", "machines"],
        checks: [
          "real generation",
          "chat palette navigation",
          "comparison",
          "review before save",
          "reuse",
          "portable save/load",
          "invalid load preservation",
          "generation failure preservation",
          "undo",
          "FreeCAD export",
          "contribution export",
          "SVG export",
          "diagram text and arrows",
          "reload persistence",
          "responsive layout",
        ],
        browserErrors: errors,
      },
      null,
      2,
    ),
  );
  console.log(
    "PASS both studio journeys with real FreeCAD generation and portable exports",
  );
} finally {
  await browser.close();
}
