import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {sources,chapters,bookMarkdown} from '../web/js/book-content.js';
const base=(process.env.STUDIO_PAGES_URL||'http://127.0.0.1:8777/iconic-tutor/').replace(/\/?$/,'/');
assert.equal(sources.length,16); assert.equal(chapters.length,6);
for (const s of sources) assert(bookMarkdown().includes(s.url));
assert.equal(sources.filter(s=>s.canon).length,1);
assert(!bookMarkdown().includes("not an official"));
assert(!bookMarkdown().includes("In the founder’s message"));
assert.match(bookMarkdown(), /experimental validation/);
assert(!chapters.find(ch=>ch.id==='projects').ladder);
assert.match(chapters.find(ch=>ch.id==='projects').title, /worth building/);
const browser=await chromium.launch({args:['--use-angle=swiftshader','--enable-webgl']});
try {
  await fs.mkdir('reports/book-browser',{recursive:true});
  const page=await browser.newPage({viewport:{width:1440,height:1100}}), errors=[], writes=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')writes.push(r.url());});
  await page.goto(base+'studio.html');
  assert.equal(await page.locator('.lesson-picker>button,.lesson-picker>a').count(),6);
  await page.screenshot({path:'reports/book-browser/home-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'home mobile overflow');
  await page.screenshot({path:'reports/book-browser/home-mobile.png',fullPage:true});
  await page.locator('.story-feature').click();
  await page.locator('.book-chapter').first().waitFor();
  assert.equal(await page.locator('.book-chapter').count(),6);
  await page.locator('#chapter-mission button').click(); await page.reload();
  assert.match(await page.locator('#reading-progress').textContent(),/1 of 6/);
  await page.locator('#canon-only').check();
  assert.equal(await page.locator('.source-card').count(),1);
  assert.match(await page.locator('.source-card').textContent(),/Philanthropic Franchise/);
  await page.locator('#source-search').fill('rover'); assert.equal(await page.locator('.source-card').count(),0);
  await page.locator('#canon-only').uncheck(); assert.equal(await page.locator('.source-card').count(),1);
  await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));
  assert.equal(await page.locator('.source-card').count(),16);
  await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));
  assert.equal(await page.locator('.source-card').count(),1);
  await page.locator('#source-search').fill('');
  const book=page.waitForEvent('download');await page.locator('#download-book').click();
  const download=await book;assert.equal(download.suggestedFilename(),'mini-ose-book.md');
  assert.equal(await fs.readFile(await download.path(),'utf8'),bookMarkdown());
  await page.locator('#story-audience').selectOption('supporter');
  assert.match(await page.locator('#audience-prompt').textContent(),/experiment/);
  for(const name of ['possibility','example','unknown','invitation'])await page.locator(`[name=${name}]`).fill('Personal test: <script>not executable</script>');
  const story=page.waitForEvent('download');await page.locator('#story-form button').click();assert.equal((await story).suggestedFilename(),'my-ose-story.md');
  await page.reload();assert.equal(await page.locator('#story-audience').inputValue(),'supporter');assert.match(await page.locator('[name=possibility]').inputValue(),/Personal test/);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'book mobile overflow');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'reports/book-browser/book-mobile.png'});
  await page.setViewportSize({width:1440,height:1100});await page.goto(base+'book.html');
  await page.screenshot({path:'reports/book-browser/book-desktop.png'});
  await page.goto(base+'book.html#chapter-projects');
  assert(await page.locator('#chapter-projects').evaluate(el=>Math.abs(el.getBoundingClientRect().top)<80),'direct chapter link');
  assert.equal(await page.locator('.site-credit a').getAttribute('href'),'https://www.goodancestor.com');
  assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);
  console.log('PASS landing layout, six chapters, sixteen sources, canon filter, reading/story persistence, downloads, print contents, mobile and direct chapter links');
} finally {await browser.close();}
